@startuml
title Usecase for Information system
left to right direction
skinparam packageStyle rect
actor Друзі
actor Користувач
actor Художник_споживач
actor Робітник_зі_складу_фарб
actor Спеціаліст_з_освітлення
actor сервіс_E_Pay
actor Спеціаліст_з_освітлення
actor Google_Search_API

rectangle Software {
  
  Користувач <|-- Друзі
  Користувач <|-- Художник_споживач
  Користувач -- (Авторизувати користувача)
  
  Друзі -- (Оцінити живопис)
  Друзі -->(Створити замовлення)
  Художник_споживач -- (Замовити потрібні фарби)
  Художник_споживач -- (Створити живопис)
  Художник_споживач -- (Сплатити рахунок)
  (Сплатити рахунок) --> Спеціаліст_з_освітлення

  Робітник_зі_складу_фарб --> (Виконати вимогу)
  (Сплатити рахунок) --> Робітник_зі_складу_фарб
  (Замовити потрібні фарби) --> Робітник_зі_складу_фарб
  Спеціаліст_з_освітлення --> (Виконати вимогу)
  (Сформувати вимоги з освітлення) --> Спеціаліст_з_освітлення
  
  (Сплатити рахунок) ..> (Авторизувати користувача) : <<include>>
 
  (Замовити потрібні фарби) ..> (Авторизувати користувача)  : <<include>>
  (Створити живопис) ..> (Авторизувати користувача)  : <<include>>
  (Оплатити через E-сплату) ..> (Сплатити рахунок)  : <<extend>>
  (Виконати вимогу) ..> (Авторизувати користувача) : <<include>> 
  
  (Завести друзів) ..> (Авторизувати користувача) : <<include>>
  (Сформувати вимоги з освітлення) ..> (Авторизувати користувача) : <<include>>
  (Створити Online-запит) ..> (Сформувати вимоги з освітлення) : <<extend>>
  (Створити Online-запит) ..> (Замовити потрібні фарби) : <<extend>>
  
  (Оцінити живопис) ..> (Авторизувати користувача)  : <<include>>
  (Створити замовлення) ..> (Авторизувати користувача)  : <<include>>
  
  Художник_споживач -- (Завести друзів)
  Художник_споживач -- (Сформувати вимоги з освітлення)
  сервіс_E_Pay -- (Оплатити через E-сплату)
  Google_Search_API -- (Створити Online-запит)
  Художник_споживач -- (Виконати вимогу)
}
@enduml
